<?php
$url = "http://app-tree.co.uk/icargoN/track.php";

$data_string = '{"from":{"name":"Nishant","company":"1 Manor Farm Barns","street1":"1 Manor Farm Barns","street2":"Henton","city":"1 Manor Farm Barns","state":"Oxfordshire","zip":"OX39 4AE","country_name":"England","alpha3_code":"GBR"},"to":{"zip":"OX39 4AE","alpha3_code":"GBR","alpha2_code":"GB","country_name":"United Kingdom"},"ship_date":"2018-04-07","extra":{},"package":[{"packaging_type":"Parcels","width":"12","length":"12","height":"12","dimension_unit":"cm","weight":"12","weight_unit":"KG"}],"customer_id":"181","user_id":"335","booked_by":"10","carrier":"ukmail","currency":"GBP","endPointUrl":"getNextdayAvailableCarrier"}';

$data_string = '{"from":{"name":"Nishant","company":"1 Manor Farm Barns","street1":"1 Manor Farm Barns","street2":"Henton","city":"1 Manor Farm Barns","state":"Oxfordshire","zip":"OX39 4AE","alpha3_code":"GBR","country_name":"England"},"to":{"zip":"OX39 4PU","alpha3_code":"GBR","alpha2_code":"GB","country_name":"United Kingdom"},"ship_date":"2018-04-11","extra":{},"package":[{"packaging_type":"Parcels","width":"12","length":"12","height":"12","dimension_unit":"cm","weight":"12","weight_unit":"KG"}],"customer_id":"181","user_id":"335","booked_by":"10","carrier":"ukmail","currency":"GBP","email":"5ways@gmail.com","access_token":"MTU1NTc0MDMwOS01YWNiMzIyMzc2YjQzLTEw","company_id":"10","endPointUrl":"getNextdayAvailableCarrier"}';

$data_string = '{"parcel":{"0":{"package":"Parcels","qty":"1","weight":"12","length":"12","width":"12","height":"12"}},"customer":{"name":"Pooja Singh","email":"pooja1712@gmail.com","id":"181","users":[{"id":"181","name":"Pooja Singh","email":"pooja1712@gmail.com","is_default":0,"collection_address":{"user_id":"181","address_line1":"1 Manor Farm Barns","address_line2":"Henton","postcode":"OX39 4AE","city":"Chinnor","country":"England","latitude":"51.71613790","longitude":"-0.89684690","state":"Oxfordshire","company_name":"","name":null,"phone":null,"email":null}},{"id":"335","name":"Nishant","email":"nishant.verma121@ordercup.com","is_default":"1","collection_address":{"user_id":"335","address_line1":"1 Manor Farm Barns","address_line2":"Henton","postcode":"OX39 4AE","city":"Chinnor","country":"England","latitude":"51.71613790","longitude":"-0.89684690","state":"Oxfordshire","company_name":"","name":null,"phone":null,"email":null}},{"id":"336","name":"Test User","email":"testing110@gmail.com","is_default":"0","collection_address":null}],"default_user_id":"335"},"collection_postcode":"OX39 4AE","user":{"id":"335","name":"Nishant","email":"nishant.verma121@ordercup.com","is_default":"1","collection_address":{"user_id":"335","address_line1":"1 Manor Farm Barns","address_line2":"Henton","postcode":"OX39 4AE","city":"Chinnor","country":"England","latitude":"51.71613790","longitude":"-0.89684690","state":"Oxfordshire","company_name":"","name":null,"phone":null,"email":null}},"service_date":"2018-04-11","delivery_country":{"id":"235","short_name":"United Kingdom","alpha2_code":"GB","alpha3_code":"GBR","numeric_code":"826"},"delivery_postcode":"OX39 4PU","carrier_code":{"0":"ukmail"},"service_name":{"0":"Next working day"},"carrier_cost":{"0":"4.5"},"customer_cost":{"0":"4.5"},"collection":{"0":"1","postcode":"OX39 4AE","address_line1":"H-140","address_line2":"5th Floor","city":"Noida","county":"UP","country":"India","email":"nishant.v@perceptive-solutions.com","name":"Nishant 1","phone":"9999999999","instruction":"Pickup Instructions"},"service_code":"1","carrier_code_str":"ukmail","collection_str":"1","service_name_str":"Next working day","carrier_cost_str":"4.5","customer_cost_str":"4.5","delivery":{"postcode":"OX39 4PU","instruction":"Delivery Instructions","address_line1":"Auram Avenue","address_line2":"2nd Floor","city":"Pune","county":"Maharashtra","country":"India","email":"nishant.verma@ordercup.com","name":"Nishant sharma","phone":"8888888888"},"customer_reference":"Customer Reference","customer_description":"Customer Descripation","insurance_value":"13","insurance_opted":true,"insurance_currency":"GBP","special":{"1":true,"2":true,"3":true,"4":true,"5":true,"6":true,"7":true,"8":true},"email":"5ways@gmail.com","access_token":"MTU1NTc0MDMwOS01YWNiMzIyMzc2YjQzLTEw","company_id":"10","endPointUrl":"bookNextDayJob"}';

$data_string = '{"from":{"name":"Nishant","company":"1 Manor Farm Barns","street1":"1 Manor Farm Barns","street2":"Henton","city":"1 Manor Farm Barns","state":"Oxfordshire","zip":"OX39 4AE","alpha3_code":"GBR","country_name":"England"},"to":{"zip":"OX39 4BX","alpha3_code":"GBR","alpha2_code":"GB","country_name":"United Kingdom"},"ship_date":"2018-04-12","extra":{},"package":[{"packaging_type":"Parcels","width":"12","length":"12","height":"12","dimension_unit":"cm","weight":"12","weight_unit":"KG"}],"customer_id":"181","user_id":"335","booked_by":"10","carrier":"ukmail","currency":"GBP","email":"5ways@gmail.com","access_token":"MTU1NTc0MDMwOS01YWNiMzIyMzc2YjQzLTEw","company_id":"10","endPointUrl":"getNextdayAvailableCarrier"}';

$data_string = '{"customer_id":"312","collection_user_id":"362","service_date":"2018-04-13 12:47","transit_time":1399,"transit_distance":5038,"transit_time_text":"23 mins 19 seconds","transit_distance_text":"3.13 mi","service_detail":{"service_name":"standard_same_day","rate_type":"Distance","message":null,"currency":"GBP","total_price":"25.95","courier_commission":"0.00","courier_commission_value":0,"base_price":24.95,"charge_from_base":false,"icon":"/icons/original/missing.png","max_delivery_time":"06:35:03","dimensions":{"length":12,"width":12,"height":12,"unit":"IN"},"weight":{"weight":200,"unit":"KG"},"time":{"max_waiting_time":60,"unit":"MIN"},"taxes":{"total_tax":4.99},"surcharges":{"same_day_drop_surcharge":1}},"warehouse_latitude":"51.68062780000000000000","warehouse_longitude":"-1.41638070000000000000","warehouse_id":"83","collection_address":{"OX3 7BW":{"address_line1":"9B Windmill Road","address_line2":"Headington","address_origin":"local","city":"Oxford","country":"England","email":"meenakshi@perceptive-solutions.com","latitude":"51.75935580","longitude":"-1.21019110","name":"Meenakshi","phone":null,"postcode":"OX3 7BW","state":"Oxfordshire","type":"","notification":1,"special_instruction":""}},"delivery_address":{"OX3 9DU":{"address_line1":"Headley Way","address_line2":"Headington","address_origin":"api","city":"Oxford","country":"England","email":"meenakshi@perceptive-solutions.com","latitude":51.7638706,"longitude":-1.2198062999999593,"postcode":"OX3 9DU","state":"Oxfordshire","type":"","notification":1,"special_instruction":""},"OX3 7LE":{"address_line1":"Old Road","address_line2":"Headington","address_origin":"api","city":"Oxford","country":"England","email":"meenakshi@perceptive-solutions.com","latitude":51.7506772,"longitude":-1.18006749999995,"postcode":"OX3 7LE","state":"Oxfordshire","type":"","notification":1,"special_instruction":"meenakshi@perceptive-solutions.com"}},"userid":"298","email":"deepakpcs@gmail.com","access_token":"MjA3ODk4NTA5Ny01YWQwNTQzZjdhNTY3LTI5OA==","company_id":"298","endPointUrl":"bookShipment"}';
$useragent = 'Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/534.10 (KHTML, like Gecko)
Chrome/8.0.552.224: Safari/534.10'; // notice this


$ch=curl_init($url);

curl_setopt_array($ch, array(
    CURLOPT_POST => true,
    CURLOPT_POSTFIELDS => $data_string,
    //CURLOPT_HEADER => true,
    CURLOPT_RETURNTRANSFER => 1,
    CURLOPT_HTTPHEADER => array('Content-Type:application/json', 'Content-Length: ' . strlen($data_string))
));

$result = curl_exec($ch);
curl_close($ch);

print_r($result);