CREATE TABLE IF NOT EXISTS `icargo_ukmail_tracking` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `consignmentNumber` varchar(255) NOT NULL,
  `load_identity` varchar(255) NOT NULL,
  `collectionDate` varchar(255) NOT NULL,
  `originalDelivery` varchar(255) NOT NULL,
  `expectedDelivery` varchar(255) NOT NULL,
  `estimatedTimeOfArrivalStart` varchar(255) NOT NULL,
  `estimatedTimeOfArrivalEnd` varchar(255) NOT NULL,
  `quantity` int(11) NOT NULL,
  `weight` int(11) NOT NULL,
  `foundConsignment` varchar(255) NOT NULL,
  `companyName` varchar(255) NOT NULL,
  `postalTown` varchar(255) NOT NULL,
  `international` varchar(255) NOT NULL,
  `mail` varchar(255) NOT NULL,
  `mailingID` varchar(255) NOT NULL,
  `swapOut` varchar(255) NOT NULL,
  `returnConsignmentNumber` varchar(255) NOT NULL,
  `subEmail` varchar(255) NOT NULL,
  `subInstructions` varchar(255) NOT NULL,
  `subName` varchar(255) NOT NULL,
  `subPhone` varchar(255) NOT NULL,
  `subRef1` varchar(255) NOT NULL,
  `subRef2` varchar(255) NOT NULL,
  `subSequence` int(1) NOT NULL,
  `podDescription` varchar(255) NOT NULL,
  `podQuantity` int(11) NOT NULL,
  `podSequence` int(11) NOT NULL,
  `podTimeStamp` varchar(255) NOT NULL,
  `podRecipientName` varchar(255) NOT NULL,
  `podDeliveryComments` varchar(255) NOT NULL,
  `podDeliveryTypeCode` varchar(255) NOT NULL,
  `statusCode` int(11) NOT NULL,
  `statusMessage` varchar(255) NOT NULL,
  `resultState` varchar(255) NOT NULL,
  `errors` varchar(255) NOT NULL,
  `createdOn` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB